### ISSUE TITLE
mockupy - main page, "product" - list

### ISSUE THREAD

**Issue by tokuchar** [tokuchar/shop-sandbox#19]
justinmind :)

**Comment by tokuchar** [comment]
Propozycja wyglądu:
![image](https://user-images.githubusercontent.com/30174319/91580888-07743a80-e94e-11ea-8061-0ebcf6cf3866.png)

**Comment by tokuchar** [comment]
Ania, zatwierdź plis :D

**Comment by AnnLas** [comment]
Design już kiedyś gdzieś widziałam xd jak na pierwszą wersję spoko, potem może jakieś kolory dodamy czy coś 👍
